# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ComputerOrganization/cpu54/cpu54.cache/wt [current_project]
set_property parent.project_path D:/ComputerOrganization/cpu54/cpu54.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/大二下课程/计算机组成原理/test2019_for_cpu54.coe
add_files D:/大二下课程/计算机组成原理/tmp.coe
add_files c:/Users/Stewart1999/Desktop/tmp.coe
add_files -quiet D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
add_files -quiet d:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files d:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_mem D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/dist_mem_gen_0.mif
read_verilog -library xil_defaultlib {
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/Register_Files.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/PC_Joint.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/PC.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/NPC.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_RF_Write.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_RF_rd.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_PC.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_LO.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_HI.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_CP0_exc.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_ALU_B.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/MUX_ALU_A.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/HI_LO.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/Extend_8_32.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/Extend_16_32.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/Divider_Ins.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/CP0.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/Control_Unit.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/ALU.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/5_32_extend.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/16_32_extend.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/seg7x16.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/DMEM_temp.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/cpu.v
  D:/ComputerOrganization/cpu54/cpu54.srcs/sources_1/imports/cpu54/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ComputerOrganization/cpu54/cpu54.srcs/constrs_1/new/first_board.xdc
set_property used_in_implementation false [get_files D:/ComputerOrganization/cpu54/cpu54.srcs/constrs_1/new/first_board.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
